#@endpoint = https://10f4z51fy3.execute-api.us-east-1.amazonaws.com/prod
@endpoint = https://ar10dtwcme.execute-api.us-east-1.amazonaws.com/prod/

#GET {{endpoint}}/hello
###

GET {{endpoint}}/spaces?spaceId=fd083169-26b4-482a-8b14-fdbe3e6f0588
###

GET {{endpoint}}/spaces?location=London
###

POST {{endpoint}}/spaces/
Content-Type: : application/json

{
    "location": "London",
    "name": "Best location"
}
###

PUT {{endpoint}}/spaces/?spaceId=fd083169-26b4-482a-8b14-fdbe3e6f0588
Content-Type: : application/json

{
    "location": "Bari",
}
###